/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import domain.Cena;
import domain.Proizvod;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import tables.TableCena;
import tables.TableProizvod;
import view.controller.ViewController;

/**
 *
 * @author trifu
 */
public class Frm2nf extends javax.swing.JDialog {

    /**
     * Creates new form Frm2nf
     */
    public Frm2nf(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btnIzmeni.setBackground(Color.PINK);
        btnIzmeniCenu.setBackground(Color.PINK);
        btnPopuniCenu.setBackground(Color.PINK);
        btnPopuniProizvod.setBackground(Color.PINK);
        btnUnesi.setBackground(Color.PINK);
        btnUnesiCenu.setBackground(Color.PINK);

        try {
            prepareView();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error in view initialization!\n" + e.getMessage(), "View 3nf form error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCena = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProizvod = new javax.swing.JTable();
        lblCena = new javax.swing.JLabel();
        lblProizvod = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblSifraProizvoda = new javax.swing.JLabel();
        txtSifraProizvoda = new javax.swing.JTextField();
        lblNazivProizvoda = new javax.swing.JLabel();
        txtNazivProizvoda = new javax.swing.JTextField();
        txtOpis = new javax.swing.JTextField();
        lblOpis = new javax.swing.JLabel();
        lblZapremina = new javax.swing.JLabel();
        txtZapremina = new javax.swing.JTextField();
        btnUnesi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        lblTipProizvoda = new javax.swing.JLabel();
        lblJedinicaMereStr = new javax.swing.JLabel();
        txtTipProizvoda = new javax.swing.JTextField();
        txtJedinicaMereStr = new javax.swing.JTextField();
        btnPopuniProizvod = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblSifraProizvoda1 = new javax.swing.JLabel();
        txtSifraProizvodaCena = new javax.swing.JTextField();
        lblSifraCene = new javax.swing.JLabel();
        txtSifraCene = new javax.swing.JTextField();
        txtSifraPDV = new javax.swing.JTextField();
        lblSifraPDV = new javax.swing.JLabel();
        lblNazivProizvodaCena = new javax.swing.JLabel();
        txtNazivProizvodaCena = new javax.swing.JTextField();
        lblVrednost = new javax.swing.JLabel();
        txtVrednost = new javax.swing.JTextField();
        btnUnesiCenu = new javax.swing.JButton();
        btnIzmeniCenu = new javax.swing.JButton();
        btnPopuniCenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblCena.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCena);

        tblProizvod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblProizvod);

        lblCena.setText("Cena:");

        lblProizvod.setText("Proizvod:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 102, 102))); // NOI18N

        lblSifraProizvoda.setText("Sifra proizvoda:");

        lblNazivProizvoda.setText("Naziv proizvoda:");

        lblOpis.setText("Opis:");

        lblZapremina.setText("Zapremina:");

        btnUnesi.setText("Unesi");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        lblTipProizvoda.setText("Tip proizvoda:");

        lblJedinicaMereStr.setText("Jedinica mere:");

        btnPopuniProizvod.setText("Popuni formu za izmenu");
        btnPopuniProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopuniProizvodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSifraProizvoda)
                            .addComponent(lblNazivProizvoda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSifraProizvoda)
                            .addComponent(txtNazivProizvoda, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblZapremina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(txtZapremina, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTipProizvoda)
                        .addGap(18, 18, 18)
                        .addComponent(txtTipProizvoda)))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOpis)
                            .addComponent(lblJedinicaMereStr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOpis)
                            .addComponent(txtJedinicaMereStr)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPopuniProizvod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUnesi)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSifraProizvoda)
                    .addComponent(txtSifraProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOpis))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNazivProizvoda)
                    .addComponent(txtNazivProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZapremina)
                    .addComponent(txtZapremina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJedinicaMereStr)
                    .addComponent(txtJedinicaMereStr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipProizvoda)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTipProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUnesi)
                        .addComponent(btnIzmeni)
                        .addComponent(btnPopuniProizvod))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 102, 102))); // NOI18N

        lblSifraProizvoda1.setText("Sifra proizvoda:");

        lblSifraCene.setText("Sifra cene:");

        lblSifraPDV.setText("Sifra PDV:");

        lblNazivProizvodaCena.setText("Naziv proizvoda:");

        txtNazivProizvodaCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivProizvodaCenaActionPerformed(evt);
            }
        });

        lblVrednost.setText("Vrednost:");

        btnUnesiCenu.setText("Unesi");
        btnUnesiCenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiCenuActionPerformed(evt);
            }
        });

        btnIzmeniCenu.setText("Izmeni");
        btnIzmeniCenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniCenuActionPerformed(evt);
            }
        });

        btnPopuniCenu.setText("Popuni formu za izmenu");
        btnPopuniCenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopuniCenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblSifraProizvoda1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblSifraCene)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSifraProizvodaCena)
                            .addComponent(txtSifraCene, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblVrednost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(txtVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSifraPDV)
                    .addComponent(lblNazivProizvodaCena)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnIzmeniCenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPopuniCenu)))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSifraPDV)
                    .addComponent(txtNazivProizvodaCena)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUnesiCenu)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSifraProizvoda1)
                    .addComponent(txtSifraProizvodaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSifraPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSifraPDV))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSifraCene)
                    .addComponent(txtSifraCene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNazivProizvodaCena)
                    .addComponent(txtNazivProizvodaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVrednost)
                            .addComponent(txtVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPopuniCenu)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIzmeniCenu)
                            .addComponent(btnUnesiCenu))))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProizvod)
                            .addComponent(lblCena))
                        .addGap(406, 406, 406)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(668, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProizvod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(181, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        try {
            Proizvod proizvod = new Proizvod();
            proizvod.setSifraProizvoda(Long.parseLong(txtSifraProizvoda.getText().trim()));

            proizvod.setNazivProizvoda(txtNazivProizvoda.getText().trim());
            proizvod.setZapremina(Double.parseDouble(txtZapremina.getText().trim()));
            proizvod.setOpis(txtOpis.getText().trim());
            proizvod.setTipProizvoda(Long.parseLong(txtTipProizvoda.getText().trim()));
            proizvod.setJedMereStr(txtJedinicaMereStr.getText().trim());

            Controller.getInstance().addProizvod(proizvod);
            JOptionPane.showMessageDialog(this, "Proizvod successfully saved!", "Insert proizvod", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openFrm2nf();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Proizvod not saved!", "Insert proizvod", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnUnesiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            Proizvod proizvod = new Proizvod();
            proizvod.setSifraProizvoda(Long.parseLong(txtSifraProizvoda.getText().trim()));

            proizvod.setNazivProizvoda(txtNazivProizvoda.getText().trim());
            proizvod.setZapremina(Double.parseDouble(txtZapremina.getText().trim()));
            proizvod.setOpis(txtOpis.getText().trim());
            proizvod.setTipProizvoda(Long.parseLong(txtTipProizvoda.getText().trim()));
            proizvod.setJedMereStr(txtJedinicaMereStr.getText().trim());

            Controller.getInstance().saveProizvod(proizvod);
            JOptionPane.showMessageDialog(this, "Proizvod successfully updated!", "Update proizvod", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openFrm2nf();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Proizvod not updated!", "Update proizvod", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnUnesiCenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiCenuActionPerformed
        try {
            Cena cena = new Cena();
            cena.setSifraProizvoda(Long.parseLong(txtSifraProizvodaCena.getText().trim()));
            cena.setSifraCene(Long.parseLong(txtSifraCene.getText().trim()));
            cena.setVrednost(Double.parseDouble(txtVrednost.getText().trim()));
            cena.setSifraPDV(Long.parseLong(txtSifraPDV.getText().trim()));
            Controller.getInstance().addCena(cena);
            JOptionPane.showMessageDialog(this, "Cena successfully saved!", "Insert cena", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openFrm2nf();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Cena not saved!", "Insert cena", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUnesiCenuActionPerformed

    private void btnIzmeniCenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniCenuActionPerformed
        try {
            Cena cena = new Cena();
            cena.setSifraProizvoda(Long.parseLong(txtSifraProizvodaCena.getText().trim()));
            cena.setSifraCene(Long.parseLong(txtSifraCene.getText().trim()));
            cena.setVrednost(Double.parseDouble(txtVrednost.getText().trim()));
            cena.setSifraPDV(Long.parseLong(txtSifraPDV.getText().trim()));
            cena.setNazivProizvoda(txtNazivProizvodaCena.getText().trim());
            Controller.getInstance().saveCena(cena);
            JOptionPane.showMessageDialog(this, "Cena successfully updated!", "Update cena", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openFrm2nf();

        } catch (Exception ex) {

            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Cena not updated!", "Update cena", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeniCenuActionPerformed

    private void txtNazivProizvodaCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivProizvodaCenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazivProizvodaCenaActionPerformed

    private void btnPopuniCenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopuniCenuActionPerformed
        popnuCenu();
    }//GEN-LAST:event_btnPopuniCenuActionPerformed

    private void btnPopuniProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopuniProizvodActionPerformed
        popuniProizvod();
    }//GEN-LAST:event_btnPopuniProizvodActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnIzmeniCenu;
    private javax.swing.JButton btnPopuniCenu;
    private javax.swing.JButton btnPopuniProizvod;
    private javax.swing.JButton btnUnesi;
    private javax.swing.JButton btnUnesiCenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCena;
    private javax.swing.JLabel lblJedinicaMereStr;
    private javax.swing.JLabel lblNazivProizvoda;
    private javax.swing.JLabel lblNazivProizvodaCena;
    private javax.swing.JLabel lblOpis;
    private javax.swing.JLabel lblProizvod;
    private javax.swing.JLabel lblSifraCene;
    private javax.swing.JLabel lblSifraPDV;
    private javax.swing.JLabel lblSifraProizvoda;
    private javax.swing.JLabel lblSifraProizvoda1;
    private javax.swing.JLabel lblTipProizvoda;
    private javax.swing.JLabel lblVrednost;
    private javax.swing.JLabel lblZapremina;
    private javax.swing.JTable tblCena;
    private javax.swing.JTable tblProizvod;
    private javax.swing.JTextField txtJedinicaMereStr;
    private javax.swing.JTextField txtNazivProizvoda;
    private javax.swing.JTextField txtNazivProizvodaCena;
    private javax.swing.JTextField txtOpis;
    private javax.swing.JTextField txtSifraCene;
    private javax.swing.JTextField txtSifraPDV;
    private javax.swing.JTextField txtSifraProizvoda;
    private javax.swing.JTextField txtSifraProizvodaCena;
    private javax.swing.JTextField txtTipProizvoda;
    private javax.swing.JTextField txtVrednost;
    private javax.swing.JTextField txtZapremina;
    // End of variables declaration//GEN-END:variables

    private void prepareView() throws Exception {
        setTitle("2NF");
        filTableProizvod();
        fillTableCena();
    }

    private void filTableProizvod() throws Exception {
        List<Proizvod> proizvod = Controller.getInstance().getAllProizvod();
        TableProizvod model = new TableProizvod(proizvod);
        tblProizvod.setModel(model);
    }

    private void fillTableCena() throws Exception {
        List<Cena> cena = Controller.getInstance().getAllCena();
        TableCena model = new TableCena(cena);
        tblCena.setModel(model);
    }

    private void popnuCenu() {

        int c = tblCena.getSelectedRow();
        TableCena tc = (TableCena) tblCena.getModel();
        Cena cena = tc.getCena(c);

        txtSifraProizvodaCena.setText(cena.getSifraProizvoda() + "");
        txtSifraCene.setText(cena.getSifraCene() + "");
        txtVrednost.setText(cena.getVrednost() + "");
        txtSifraPDV.setText(cena.getSifraPDV() + "");

    }

    private void popuniProizvod() {
        int p = tblProizvod.getSelectedRow();
        TableProizvod tp = (TableProizvod) tblProizvod.getModel();
        Proizvod proizvod = tp.getProizvod(p);

        txtSifraProizvoda.setText(proizvod.getSifraProizvoda() + "");
        txtNazivProizvoda.setText(proizvod.getNazivProizvoda());
        txtZapremina.setText(proizvod.getZapremina() + "");
        txtOpis.setText(proizvod.getOpis());
        txtTipProizvoda.setText(proizvod.getTipProizvoda() + "");
        txtJedinicaMereStr.setText(proizvod.getJedMereStr());
    }
}
