/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import domain.Proizvod;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import tables.TableProizvod;
import view.controller.ViewController;

/**
 *
 * @author trifu
 */
public class FrmHardCoded extends javax.swing.JDialog {

    /**
     * Creates new form FrmHardCoded
     */
    public FrmHardCoded(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btnIzmeni.setBackground(Color.PINK);
        btnObrisi.setBackground(Color.PINK);
        btnPopuniPoljaProizvod.setBackground(Color.PINK);
        btnUnesi.setBackground(Color.PINK);

        try {
            prepareView();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error in view initialization!\n" + e.getMessage(), "View nalozi form error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSifraProizvoda = new javax.swing.JLabel();
        txtSifraProizvoda = new javax.swing.JTextField();
        lblNazivProizvoda = new javax.swing.JLabel();
        txtNazivProizvoda = new javax.swing.JTextField();
        txtOpis = new javax.swing.JTextField();
        lblOpis = new javax.swing.JLabel();
        lblZapremina = new javax.swing.JLabel();
        txtZapremina = new javax.swing.JTextField();
        btnUnesi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        lblTipProizvoda = new javax.swing.JLabel();
        lblJedinicaMereStr = new javax.swing.JLabel();
        txtTipProizvoda = new javax.swing.JTextField();
        txtJedinicaMereStr = new javax.swing.JTextField();
        btnPopuniPoljaProizvod = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProizvod = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unos,izmena i brisanje proizvoda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 102, 102))); // NOI18N

        lblSifraProizvoda.setText("Sifra proizvoda:");

        lblNazivProizvoda.setText("Naziv proizvoda:");

        lblOpis.setText("Opis:");

        lblZapremina.setText("Zapremina:");

        btnUnesi.setText("Unesi");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        lblTipProizvoda.setText("Tip proizvoda:");

        lblJedinicaMereStr.setText("Jedinica mere:");

        btnPopuniPoljaProizvod.setText("Popuni polja za izmenu");
        btnPopuniPoljaProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopuniPoljaProizvodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSifraProizvoda)
                            .addComponent(lblNazivProizvoda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSifraProizvoda)
                            .addComponent(txtNazivProizvoda, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblZapremina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(txtZapremina, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTipProizvoda)
                        .addGap(18, 18, 18)
                        .addComponent(txtTipProizvoda)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOpis)
                                    .addComponent(lblJedinicaMereStr))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOpis)
                                    .addComponent(txtJedinicaMereStr)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addComponent(btnObrisi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIzmeni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUnesi)
                                .addGap(24, 24, 24)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPopuniPoljaProizvod)
                        .addGap(54, 54, 54))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSifraProizvoda)
                    .addComponent(txtSifraProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOpis))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNazivProizvoda)
                    .addComponent(txtNazivProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZapremina)
                    .addComponent(txtZapremina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJedinicaMereStr)
                    .addComponent(txtJedinicaMereStr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipProizvoda)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTipProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPopuniPoljaProizvod)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnesi)
                    .addComponent(btnIzmeni)
                    .addComponent(btnObrisi))
                .addContainerGap())
        );

        tblProizvod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProizvod);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        try {
            Proizvod proizvod = new Proizvod();
            proizvod.setSifraProizvoda(Long.parseLong(txtSifraProizvoda.getText().trim()));

            proizvod.setNazivProizvoda(txtNazivProizvoda.getText().trim());
            proizvod.setZapremina(Double.parseDouble(txtZapremina.getText().trim()));
            proizvod.setOpis(txtOpis.getText().trim());
            proizvod.setTipProizvoda(Long.parseLong(txtTipProizvoda.getText().trim()));
            proizvod.setJedMereStr(txtJedinicaMereStr.getText().trim());

            Controller.getInstance().addProizvod(proizvod);
            JOptionPane.showMessageDialog(this, "Proizvod successfully saved!", "Insert proizvod", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openFrmHardCoded();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Proizvod not saved!", "Insert proizvod", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnUnesiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            Proizvod proizvod = new Proizvod();
            proizvod.setSifraProizvoda(Long.parseLong(txtSifraProizvoda.getText().trim()));

            proizvod.setNazivProizvoda(txtNazivProizvoda.getText().trim());
            proizvod.setZapremina(Double.parseDouble(txtZapremina.getText().trim()));
            proizvod.setOpis(txtOpis.getText().trim());
            proizvod.setTipProizvoda(Long.parseLong(txtTipProizvoda.getText().trim()));
            proizvod.setJedMereStr(txtJedinicaMereStr.getText().trim());

            Controller.getInstance().saveProizvod(proizvod);
            JOptionPane.showMessageDialog(this, "Proizvod successfully updated!", "Update proizvod", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openFrmHardCoded();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Proizvod not updated!", "Update proizvod", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        try {
            Proizvod proizvod = new Proizvod();
            proizvod.setSifraProizvoda(Long.parseLong(txtSifraProizvoda.getText().trim()));
            Controller.getInstance().deleteProizvod(proizvod);
            JOptionPane.showMessageDialog(this, "Proizvod successfully deleted!", "Delete proizvod", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openFrmHardCoded();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Proizvod nije obrisan!", "Delete proizvod", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnPopuniPoljaProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopuniPoljaProizvodActionPerformed
        popuniPolja();
    }//GEN-LAST:event_btnPopuniPoljaProizvodActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPopuniPoljaProizvod;
    private javax.swing.JButton btnUnesi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJedinicaMereStr;
    private javax.swing.JLabel lblNazivProizvoda;
    private javax.swing.JLabel lblOpis;
    private javax.swing.JLabel lblSifraProizvoda;
    private javax.swing.JLabel lblTipProizvoda;
    private javax.swing.JLabel lblZapremina;
    private javax.swing.JTable tblProizvod;
    private javax.swing.JTextField txtJedinicaMereStr;
    private javax.swing.JTextField txtNazivProizvoda;
    private javax.swing.JTextField txtOpis;
    private javax.swing.JTextField txtSifraProizvoda;
    private javax.swing.JTextField txtTipProizvoda;
    private javax.swing.JTextField txtZapremina;
    // End of variables declaration//GEN-END:variables

    private void prepareView() throws Exception {
        setTitle("HARD CODED TEHNIKA OPTIMIZACIJE");
        fillTableProizvod();
    }

    private void fillTableProizvod() throws Exception {
        List<Proizvod> proizvod = Controller.getInstance().getAllProizvodi();
        TableProizvod model = new TableProizvod(proizvod);
        tblProizvod.setModel(model);
    }

    private void popuniPolja() {
        int p = tblProizvod.getSelectedRow();
        TableProizvod tp = (TableProizvod) tblProizvod.getModel();
        Proizvod proizvod = tp.getProizvod(p);

        txtSifraProizvoda.setText(proizvod.getSifraProizvoda() + "");
        txtNazivProizvoda.setText(proizvod.getNazivProizvoda());
        txtZapremina.setText(proizvod.getZapremina() + "");
        txtOpis.setText(proizvod.getOpis());
        txtTipProizvoda.setText(proizvod.getTipProizvoda() + "");
        txtJedinicaMereStr.setText(proizvod.getJedMereStr());
    }
}
