/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import domain.PravnoLiceDetalji;

import domain.RacunList;
import domain.RacuniPouzecem;
import domain.RacuniVirmanom;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import tables.TablePravnoLiceDetalji;
import tables.TablePravnoLiceOsnovno;
import tables.TableProizvod;
import tables.TableRacun;
import tables.TableRacunPouzecem;
import tables.TableRacunVirmanom;
import view.controller.ViewController;

/**
 *
 * @author trifu
 */
public class FrmHorizontalno extends javax.swing.JDialog {

    /**
     * Creates new form FrmHorizontalno
     */
    public FrmHorizontalno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btnUnesi.setBackground(Color.PINK);
        btnIzmeni.setBackground(Color.PINK);
        btnIzbrisi.setBackground(Color.PINK);
        btnPopuniPolja.setBackground(Color.PINK);

        try {
            prepareView();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error in view initialization!\n" + e.getMessage(), "View nalozi form error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelunos = new javax.swing.JPanel();
        lblBrojRacuna = new javax.swing.JLabel();
        txtBrojRacuna = new javax.swing.JTextField();
        lblnapomena = new javax.swing.JLabel();
        txtUkupanIznos = new javax.swing.JTextField();
        lblDatumPrometaDobaraIUsluga = new javax.swing.JLabel();
        txtDatumPrometaDobaraIUsluga = new javax.swing.JTextField();
        lblNacinPlacanja = new javax.swing.JLabel();
        txtNacinPlacanja = new javax.swing.JTextField();
        btnUnesi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnIzbrisi = new javax.swing.JButton();
        lnlDatumIzdavanja = new javax.swing.JLabel();
        txtDatumIzdavanja = new javax.swing.JTextField();
        txtRokPlacanja = new javax.swing.JTextField();
        lblnapomena2 = new javax.swing.JLabel();
        txtMestoIzdavanja = new javax.swing.JTextField();
        lblMestoizdavanja = new javax.swing.JLabel();
        lblMestoisporuke = new javax.swing.JLabel();
        lblMagacin = new javax.swing.JLabel();
        lblPIB = new javax.swing.JLabel();
        txtMestoIsporuke = new javax.swing.JTextField();
        txtMagacin = new javax.swing.JTextField();
        txtPIB = new javax.swing.JTextField();
        btnPopuniPolja = new javax.swing.JButton();
        lblVirmanom = new javax.swing.JLabel();
        lblPouzecem = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVirmanom = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPouzecem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelunos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "unos,izmena i brisanje racuna", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 102, 255))); // NOI18N

        lblBrojRacuna.setText("Broj racuna:");

        lblnapomena.setText("Ukupan iznos:");

        lblDatumPrometaDobaraIUsluga.setText("Datum prometa dobara i usluga");

        lblNacinPlacanja.setText("Nacin placanja:");

        btnUnesi.setText("Unesi");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnIzbrisi.setText("Izbrisi");
        btnIzbrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbrisiActionPerformed(evt);
            }
        });

        lnlDatumIzdavanja.setText("Datum izdavanja:");

        lblnapomena2.setText("Rok placanja:");

        lblMestoizdavanja.setText("Mesto izdavanja:");

        lblMestoisporuke.setText("Mesto isporuke:");

        lblMagacin.setText("Magacin:");

        lblPIB.setText("PIB:");

        btnPopuniPolja.setText("Popuni polja za izmenu");
        btnPopuniPolja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopuniPoljaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelunosLayout = new javax.swing.GroupLayout(panelunos);
        panelunos.setLayout(panelunosLayout);
        panelunosLayout.setHorizontalGroup(
            panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelunosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnlDatumIzdavanja)
                    .addComponent(lblnapomena2)
                    .addComponent(lblMestoizdavanja)
                    .addComponent(lblnapomena)
                    .addComponent(lblBrojRacuna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMestoIzdavanja, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(txtRokPlacanja)
                    .addComponent(txtDatumIzdavanja)
                    .addGroup(panelunosLayout.createSequentialGroup()
                        .addGroup(panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBrojRacuna, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(txtUkupanIznos))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelunosLayout.createSequentialGroup()
                        .addGroup(panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDatumPrometaDobaraIUsluga, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNacinPlacanja, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMestoisporuke, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMagacin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPIB, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDatumPrometaDobaraIUsluga)
                            .addComponent(txtNacinPlacanja)
                            .addComponent(txtMestoIsporuke)
                            .addComponent(txtMagacin)
                            .addComponent(txtPIB, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelunosLayout.createSequentialGroup()
                        .addComponent(btnIzbrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUnesi))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelunosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPopuniPolja)
                .addGap(31, 31, 31))
        );
        panelunosLayout.setVerticalGroup(
            panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelunosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrojRacuna)
                    .addComponent(lblDatumPrometaDobaraIUsluga)
                    .addComponent(txtDatumPrometaDobaraIUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrojRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnapomena)
                    .addComponent(lblNacinPlacanja)
                    .addComponent(txtNacinPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelunosLayout.createSequentialGroup()
                        .addGroup(panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMestoisporuke)
                            .addComponent(txtMestoIsporuke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMagacin)
                            .addComponent(txtMagacin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPIB)
                            .addComponent(txtPIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUnesi)
                            .addComponent(btnIzmeni)
                            .addComponent(btnIzbrisi))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelunosLayout.createSequentialGroup()
                        .addGroup(panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDatumIzdavanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnlDatumIzdavanja))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRokPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnapomena2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMestoIzdavanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMestoizdavanja))))
                .addComponent(btnPopuniPolja))
        );

        lblVirmanom.setText("Virmanom");

        lblPouzecem.setText("Pouzecem");

        tblVirmanom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVirmanom);

        tblPouzecem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPouzecem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(panelunos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblPouzecem)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblVirmanom)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVirmanom)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPouzecem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        try {
            RacunList racun = new RacunList();
            racun.setBrojRacuna(Long.parseLong(txtBrojRacuna.getText().trim()));
            racun.setUkupanIznos(Double.parseDouble(txtUkupanIznos.getText().trim()));

            Date datumPrometaDobaraIUsluga = new SimpleDateFormat("dd.MM.yyyy").parse(txtDatumPrometaDobaraIUsluga.getText().trim());
            racun.setDatumPrometaDobaraIUsluga(datumPrometaDobaraIUsluga);

            racun.setNacinPlacanja(txtNacinPlacanja.getText().trim());
            Date datumIzdavanja = new SimpleDateFormat("dd.MM.yyyy").parse(txtDatumIzdavanja.getText().trim());
            racun.setDatumIzdavanja(datumIzdavanja);
            racun.setRokPlacanja(Integer.parseInt(txtRokPlacanja.getText().trim()));
            racun.setMestoIzdavanja(txtMestoIzdavanja.getText().trim());
            racun.setMestoIsporuke(txtMestoIsporuke.getText().trim());
            racun.setMagacin(txtMagacin.getText().trim());

            racun.setPIB(Long.parseLong(txtPIB.getText().trim()));
            Controller.getInstance().addRacunList(racun);
            JOptionPane.showMessageDialog(this, "Racun successfully saved!", "Insert racun", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openFrmHorizontalno();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Racun not saved!", "Insert racun", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUnesiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            RacunList racun = new RacunList();
            racun.setBrojRacuna(Long.parseLong(txtBrojRacuna.getText().trim()));
            racun.setUkupanIznos(Double.parseDouble(txtUkupanIznos.getText().trim()));

            Date datumPrometaDobaraIUsluga = new SimpleDateFormat("dd.MM.yyyy").parse(txtDatumPrometaDobaraIUsluga.getText().trim());
            racun.setDatumPrometaDobaraIUsluga(datumPrometaDobaraIUsluga);

            racun.setNacinPlacanja(txtNacinPlacanja.getText().trim());
            Date datumIzdavanja = new SimpleDateFormat("dd.MM.yyyy").parse(txtDatumIzdavanja.getText().trim());
            racun.setDatumIzdavanja(datumIzdavanja);
            racun.setRokPlacanja(Integer.parseInt(txtRokPlacanja.getText().trim()));
            racun.setMestoIzdavanja(txtMestoIzdavanja.getText().trim());
            racun.setMestoIsporuke(txtMestoIsporuke.getText().trim());
            racun.setMagacin(txtMagacin.getText().trim());

            racun.setPIB(Long.parseLong(txtPIB.getText().trim()));

            Controller.getInstance().saveListRacun(racun);
            JOptionPane.showMessageDialog(this, "Racun successfully updated!", "Update racun", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openFrmHorizontalno();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Racun not updated!", "Update racun", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnIzbrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbrisiActionPerformed
        try {
            RacunList rac = new RacunList();
            rac.setBrojRacuna(Integer.parseInt(txtBrojRacuna.getText()));
            Controller.getInstance().deleteRacunList(rac);
            JOptionPane.showMessageDialog(this, "Racun successfully deleted!", "Delete racun", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openFrmHorizontalno();

        } catch (Exception e) {
            e.printStackTrace(); 
            JOptionPane.showMessageDialog(this, "Racun not deleted!", "Delete racun", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzbrisiActionPerformed

    private void btnPopuniPoljaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopuniPoljaActionPerformed
        popuniPolja();
    }//GEN-LAST:event_btnPopuniPoljaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzbrisi;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPopuniPolja;
    private javax.swing.JButton btnUnesi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBrojRacuna;
    private javax.swing.JLabel lblDatumPrometaDobaraIUsluga;
    private javax.swing.JLabel lblMagacin;
    private javax.swing.JLabel lblMestoisporuke;
    private javax.swing.JLabel lblMestoizdavanja;
    private javax.swing.JLabel lblNacinPlacanja;
    private javax.swing.JLabel lblPIB;
    private javax.swing.JLabel lblPouzecem;
    private javax.swing.JLabel lblVirmanom;
    private javax.swing.JLabel lblnapomena;
    private javax.swing.JLabel lblnapomena2;
    private javax.swing.JLabel lnlDatumIzdavanja;
    private javax.swing.JPanel panelunos;
    private javax.swing.JTable tblPouzecem;
    private javax.swing.JTable tblVirmanom;
    private javax.swing.JTextField txtBrojRacuna;
    private javax.swing.JTextField txtDatumIzdavanja;
    private javax.swing.JTextField txtDatumPrometaDobaraIUsluga;
    private javax.swing.JTextField txtMagacin;
    private javax.swing.JTextField txtMestoIsporuke;
    private javax.swing.JTextField txtMestoIzdavanja;
    private javax.swing.JTextField txtNacinPlacanja;
    private javax.swing.JTextField txtPIB;
    private javax.swing.JTextField txtRokPlacanja;
    private javax.swing.JTextField txtUkupanIznos;
    // End of variables declaration//GEN-END:variables

    private void prepareView() throws Exception {
        setTitle("HORIZONTALNO PARTICIONISANJE");
        fillTableRacuniVirmanom();
        fillTableRacuniPouzecem();
    }

    private void fillTableRacuniVirmanom() throws Exception {
        List<RacuniVirmanom> racuniVirmanom = Controller.getInstance().getAllRacuniVirmanom();
        TableRacunVirmanom model = new TableRacunVirmanom(racuniVirmanom);
        tblVirmanom.setModel(model);
    }

    private void fillTableRacuniPouzecem() throws Exception {
        List<RacuniPouzecem> racuniPouzecem = Controller.getInstance().getAllRacuniPouzecem();
        TableRacunPouzecem model = new TableRacunPouzecem(racuniPouzecem);
        tblPouzecem.setModel(model);
    }

    private void popuniPolja() {
        int rv = tblVirmanom.getSelectedRow();
        int rp = tblPouzecem.getSelectedRow();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");

        if (rv != -1) {
            TableRacunVirmanom trv = (TableRacunVirmanom) tblVirmanom.getModel();
            RacuniVirmanom racunVirmanom = trv.getRacunVirmanom(rv);

            txtBrojRacuna.setText(racunVirmanom.getBrojRacuna() + "");
            txtUkupanIznos.setText(racunVirmanom.getUkupanIznos() + "");
            txtDatumIzdavanja.setText(sdf.format(racunVirmanom.getDatumIzdavanja()));
            txtNacinPlacanja.setText(racunVirmanom.getNacinPlacanja());
            txtRokPlacanja.setText(racunVirmanom.getRokPlacanja() + "");
            txtMestoIsporuke.setText(racunVirmanom.getMestoIsporuke());
            txtMestoIzdavanja.setText(racunVirmanom.getMestoIzdavanja());
            txtMagacin.setText(racunVirmanom.getMagacin());
            txtDatumPrometaDobaraIUsluga.setText(sdf.format(racunVirmanom.getDatumPrometaDobaraIUsluga()));
            txtPIB.setText(racunVirmanom.getPIB() + "");
            return;
        }
        if (rp != -1) {

            TableRacunPouzecem trp = (TableRacunPouzecem) tblPouzecem.getModel();
            RacuniPouzecem racunPouzecem = trp.getRacunPouzecem(rp);

            txtBrojRacuna.setText(racunPouzecem.getBrojRacuna() + "");
            txtUkupanIznos.setText(racunPouzecem.getUkupanIznos() + "");
            txtDatumIzdavanja.setText(sdf.format(racunPouzecem.getDatumIzdavanja()));
            txtNacinPlacanja.setText(racunPouzecem.getNacinPlacanja());
            txtRokPlacanja.setText(racunPouzecem.getRokPlacanja() + "");
            txtMestoIsporuke.setText(racunPouzecem.getMestoIsporuke());
            txtMestoIzdavanja.setText(racunPouzecem.getMestoIzdavanja());
            txtMagacin.setText(racunPouzecem.getMagacin());
            txtDatumPrometaDobaraIUsluga.setText(sdf.format(racunPouzecem.getDatumPrometaDobaraIUsluga()));
            txtPIB.setText(racunPouzecem.getPIB() + "");

        } else {
            JOptionPane.showMessageDialog(rootPane, "Izaberite red za izmenu");
        }
    }
}
