/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import view.controller.ViewController;

/**
 *
 * @author trifu
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        btn2NF.setBackground(Color.PINK);
        btn3NFNova.setBackground(Color.PINK);
        btnHardCoded.setBackground(Color.PINK);
        btnHorizontalnoParticionisanje.setBackground(Color.PINK);
        btnStoringDerivableValues.setBackground(Color.PINK);
        btnVertikalnoParticionisanje.setBackground(Color.PINK);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn2NF = new javax.swing.JButton();
        btnStoringDerivableValues = new javax.swing.JButton();
        btnHardCoded = new javax.swing.JButton();
        btnHorizontalnoParticionisanje = new javax.swing.JButton();
        btnVertikalnoParticionisanje = new javax.swing.JButton();
        btn3NFNova = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 204));

        btn2NF.setBackground(new java.awt.Color(255, 255, 255));
        btn2NF.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn2NF.setText("2 NF");
        btn2NF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2NFActionPerformed(evt);
            }
        });

        btnStoringDerivableValues.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnStoringDerivableValues.setText("Storing Derivable Values ");
        btnStoringDerivableValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoringDerivableValuesActionPerformed(evt);
            }
        });

        btnHardCoded.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnHardCoded.setText("Hard Coded");
        btnHardCoded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHardCodedActionPerformed(evt);
            }
        });

        btnHorizontalnoParticionisanje.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnHorizontalnoParticionisanje.setText("Horizontalno particionisanje");
        btnHorizontalnoParticionisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorizontalnoParticionisanjeActionPerformed(evt);
            }
        });

        btnVertikalnoParticionisanje.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnVertikalnoParticionisanje.setText("Vertikalno particionisanje");
        btnVertikalnoParticionisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVertikalnoParticionisanjeActionPerformed(evt);
            }
        });

        btn3NFNova.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn3NFNova.setText("3 NF");
        btn3NFNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3NFNovaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btn2NF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn3NFNova)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnHardCoded, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStoringDerivableValues)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVertikalnoParticionisanje)
                .addGap(38, 38, 38)
                .addComponent(btnHorizontalnoParticionisanje, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2NF)
                    .addComponent(btn3NFNova))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHardCoded)
                    .addComponent(btnStoringDerivableValues))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVertikalnoParticionisanje)
                    .addComponent(btnHorizontalnoParticionisanje))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn2NFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2NFActionPerformed
        ViewController.getInstance().openFrm2nf();

    }//GEN-LAST:event_btn2NFActionPerformed

    private void btnHardCodedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHardCodedActionPerformed
        ViewController.getInstance().openFrmHardCoded();


    }//GEN-LAST:event_btnHardCodedActionPerformed

    private void btnVertikalnoParticionisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVertikalnoParticionisanjeActionPerformed
        ViewController.getInstance().openFrmVertikalno();

    }//GEN-LAST:event_btnVertikalnoParticionisanjeActionPerformed

    private void btnStoringDerivableValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoringDerivableValuesActionPerformed
        ViewController.getInstance().openFrmStoringDerivableValues();


    }//GEN-LAST:event_btnStoringDerivableValuesActionPerformed

    private void btnHorizontalnoParticionisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorizontalnoParticionisanjeActionPerformed
        ViewController.getInstance().openFrmHorizontalno();


    }//GEN-LAST:event_btnHorizontalnoParticionisanjeActionPerformed

    private void btn3NFNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3NFNovaActionPerformed
        ViewController.getInstance().openNfForma3();

    }//GEN-LAST:event_btn3NFNovaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2NF;
    private javax.swing.JButton btn3NFNova;
    private javax.swing.JButton btnHardCoded;
    private javax.swing.JButton btnHorizontalnoParticionisanje;
    private javax.swing.JButton btnStoringDerivableValues;
    private javax.swing.JButton btnVertikalnoParticionisanje;
    // End of variables declaration//GEN-END:variables
}
