/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import domain.Racun;
import domain.StavkaRacuna;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import tables.TableRacun;
import tables.TableStavkaRacuna;
import view.controller.ViewController;

/**
 *
 * @author trifu
 */
public class FrmStoringDerivableValues extends javax.swing.JDialog {

    /**
     * Creates new form FrmStoringDerivableValues
     */
    public FrmStoringDerivableValues(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btnIzmeni.setBackground(Color.PINK);
        btnPopuniPolja.setBackground(Color.PINK);
        btnUnesi.setBackground(Color.PINK);

        try {
            prepareView();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error in view initialization!\n" + e.getMessage(), "View nalozi form error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsp = new javax.swing.JPanel();
        lblRednibroj = new javax.swing.JLabel();
        txtRedniBroj = new javax.swing.JTextField();
        lblBrojracuna = new javax.swing.JLabel();
        txtSifraRacuna = new javax.swing.JTextField();
        lblKolicina = new javax.swing.JLabel();
        txtKolicina = new javax.swing.JTextField();
        lblPoreskaOsnovica = new javax.swing.JLabel();
        txtPoreskaOsnovica = new javax.swing.JTextField();
        btnUnesi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRacun = new javax.swing.JTable();
        lblBarkod = new javax.swing.JLabel();
        lblUkupnaNaknada = new javax.swing.JLabel();
        lblProdajnaCenaSaRabatom = new javax.swing.JLabel();
        lblRabat = new javax.swing.JLabel();
        lblRedniBrojStavkePredracuna = new javax.swing.JLabel();
        lblBrojPredracuna = new javax.swing.JLabel();
        lblSifraProizvoda = new javax.swing.JLabel();
        txtRedniBrojStavkePredracuna = new javax.swing.JTextField();
        txtBrojPredracuna = new javax.swing.JTextField();
        txtSifraProizvoda = new javax.swing.JTextField();
        txtBarkod = new javax.swing.JTextField();
        txtUkupnaNaknada = new javax.swing.JTextField();
        txtProdajnaCenaSaRabatom = new javax.swing.JTextField();
        txtRabat = new javax.swing.JTextField();
        btnPopuniPolja = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStavkeRacuna = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelsp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unos i izmena stavke racuna", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 102, 153))); // NOI18N

        lblRednibroj.setText("Redni broj:");

        lblBrojracuna.setText("Sifra racuna:");

        lblKolicina.setText("Kolicina:");

        lblPoreskaOsnovica.setText("Poreska osnovica:");

        btnUnesi.setText("Unesi");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        tblRacun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRacun);

        lblBarkod.setText("Barkod:");

        lblUkupnaNaknada.setText("Ukupna naknada:");

        lblProdajnaCenaSaRabatom.setText("Prodajna cena sa rabatom:");

        lblRabat.setText("Rabat:");

        lblRedniBrojStavkePredracuna.setText("Redni broj stavke predracuna:");

        lblBrojPredracuna.setText("Broj predracuna:");

        lblSifraProizvoda.setText("Sifra proizvoda:");

        btnPopuniPolja.setText("Popuni polja za izmenu");
        btnPopuniPolja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopuniPoljaActionPerformed(evt);
            }
        });

        tblStavkeRacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStavkeRacuna);

        javax.swing.GroupLayout panelspLayout = new javax.swing.GroupLayout(panelsp);
        panelsp.setLayout(panelspLayout);
        panelspLayout.setHorizontalGroup(
            panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(panelspLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelspLayout.createSequentialGroup()
                        .addComponent(lblProdajnaCenaSaRabatom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProdajnaCenaSaRabatom))
                    .addGroup(panelspLayout.createSequentialGroup()
                        .addComponent(lblRednibroj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRedniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelspLayout.createSequentialGroup()
                        .addComponent(lblBarkod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBarkod, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelspLayout.createSequentialGroup()
                        .addComponent(lblUkupnaNaknada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUkupnaNaknada, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelspLayout.createSequentialGroup()
                        .addComponent(lblRabat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRabat, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelspLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtSifraRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelspLayout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addGroup(panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSifraProizvoda, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblBrojPredracuna, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(32, 32, 32)
                            .addComponent(txtSifraProizvoda))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelspLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBrojPredracuna, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelspLayout.createSequentialGroup()
                                .addGroup(panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelspLayout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(lblKolicina))
                                    .addGroup(panelspLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(lblPoreskaOsnovica)))
                                .addGap(41, 41, 41)
                                .addGroup(panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPoreskaOsnovica, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelspLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelspLayout.createSequentialGroup()
                                .addComponent(lblRedniBrojStavkePredracuna)
                                .addGap(18, 18, 18)
                                .addComponent(txtRedniBrojStavkePredracuna, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelspLayout.createSequentialGroup()
                                .addComponent(btnPopuniPolja)
                                .addGap(45, 45, 45)
                                .addComponent(btnIzmeni)
                                .addGap(48, 48, 48)
                                .addComponent(btnUnesi)))))
                .addContainerGap(398, Short.MAX_VALUE))
            .addGroup(panelspLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblBrojracuna)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        panelspLayout.setVerticalGroup(
            panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelspLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRednibroj)
                    .addComponent(txtRedniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKolicina))
                .addGap(18, 18, 18)
                .addGroup(panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrojracuna)
                    .addComponent(txtSifraRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPoreskaOsnovica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPoreskaOsnovica))
                .addGap(18, 18, 18)
                .addGroup(panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarkod)
                    .addComponent(txtBarkod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRedniBrojStavkePredracuna)
                    .addComponent(txtRedniBrojStavkePredracuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUkupnaNaknada)
                    .addComponent(txtUkupnaNaknada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBrojPredracuna)
                    .addComponent(txtBrojPredracuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRabat)
                    .addComponent(txtRabat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSifraProizvoda)
                    .addComponent(txtSifraProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdajnaCenaSaRabatom, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProdajnaCenaSaRabatom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnesi)
                    .addComponent(btnIzmeni)
                    .addComponent(btnPopuniPolja))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelsp, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            StavkaRacuna sr = new StavkaRacuna();
            sr.setRedniBrojStavkeRacuna(Long.parseLong(txtRedniBroj.getText().trim()));
            sr.setSifraRacuna(Long.parseLong(txtSifraRacuna.getText().trim()));
            sr.setKolicina(Integer.parseInt(txtKolicina.getText().trim()));
            sr.setBarkod(txtBarkod.getText().trim());
            sr.setUkupnaNaknada(Double.parseDouble(txtUkupnaNaknada.getText().trim()));
            sr.setRabat(Double.parseDouble(txtRabat.getText().trim()));
            sr.setProdajnaCenaSaRabatom(Double.parseDouble(txtProdajnaCenaSaRabatom.getText().trim()));
            sr.setPoreskaOsnovica(Double.parseDouble(txtPoreskaOsnovica.getText().trim()));
            sr.setSifraProizvoda(Long.parseLong(txtSifraProizvoda.getText().trim()));
            sr.setRedniBrojStavkePredracuna(Long.parseLong(txtRedniBrojStavkePredracuna.getText().trim()));
            sr.setBrojPredracuna(Long.parseLong(txtBrojPredracuna.getText().trim()));

            Controller.getInstance().saveStavkaRacuna(sr);
            JOptionPane.showMessageDialog(this, "Stavka racuna successfully updated!", "update stavkaRacuna", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openFrmStoringDerivableValues();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Stavka racuna not updated!", "Update nalog", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        try {
            StavkaRacuna sr = new StavkaRacuna();
            sr.setRedniBrojStavkeRacuna(Long.parseLong(txtRedniBroj.getText().trim()));
            sr.setSifraRacuna(Long.parseLong(txtSifraRacuna.getText().trim()));
            sr.setKolicina(Integer.parseInt(txtKolicina.getText().trim()));
            sr.setBarkod(txtBarkod.getText().trim());
            sr.setUkupnaNaknada(Double.parseDouble(txtUkupnaNaknada.getText().trim()));
            sr.setRabat(Double.parseDouble(txtRabat.getText().trim()));
            sr.setProdajnaCenaSaRabatom(Double.parseDouble(txtProdajnaCenaSaRabatom.getText().trim()));
            sr.setPoreskaOsnovica(Double.parseDouble(txtPoreskaOsnovica.getText().trim()));
            sr.setSifraProizvoda(Long.parseLong(txtSifraProizvoda.getText().trim()));
            sr.setRedniBrojStavkePredracuna(Long.parseLong(txtRedniBrojStavkePredracuna.getText().trim()));
            sr.setBrojPredracuna(Long.parseLong(txtBrojPredracuna.getText().trim()));

            Controller.getInstance().addStavkaRacuna(sr);
            JOptionPane.showMessageDialog(this, "Stavka racuna successfully saved!", "Insert stavkaRacuna", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openFrmStoringDerivableValues();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Stavka racuna not saved!", "Insert stavkaRacuna", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUnesiActionPerformed

    private void btnPopuniPoljaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopuniPoljaActionPerformed
        int r = tblStavkeRacuna.getSelectedRow();
        TableStavkaRacuna tsr = (TableStavkaRacuna) tblStavkeRacuna.getModel();
        StavkaRacuna stavkaRacuna = tsr.getStavkaRacuna(r);

        txtRedniBroj.setText(stavkaRacuna.getRedniBrojStavkeRacuna() + "");
        txtSifraRacuna.setText(stavkaRacuna.getSifraRacuna() + "");
        txtBarkod.setText(stavkaRacuna.getBarkod() + "");
        txtUkupnaNaknada.setText(stavkaRacuna.getUkupnaNaknada() + "");
        txtRabat.setText(stavkaRacuna.getRabat() + "");
        txtProdajnaCenaSaRabatom.setText(stavkaRacuna.getProdajnaCenaSaRabatom() + "");
        txtKolicina.setText(stavkaRacuna.getKolicina() + "");
        txtPoreskaOsnovica.setText(stavkaRacuna.getPoreskaOsnovica() + "");
        txtRedniBrojStavkePredracuna.setText(stavkaRacuna.getRedniBrojStavkePredracuna() + "");
        txtBrojPredracuna.setText(stavkaRacuna.getBrojPredracuna() + "");
        txtSifraProizvoda.setText(stavkaRacuna.getSifraProizvoda() + "");

    }//GEN-LAST:event_btnPopuniPoljaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPopuniPolja;
    private javax.swing.JButton btnUnesi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBarkod;
    private javax.swing.JLabel lblBrojPredracuna;
    private javax.swing.JLabel lblBrojracuna;
    private javax.swing.JLabel lblKolicina;
    private javax.swing.JLabel lblPoreskaOsnovica;
    private javax.swing.JLabel lblProdajnaCenaSaRabatom;
    private javax.swing.JLabel lblRabat;
    private javax.swing.JLabel lblRedniBrojStavkePredracuna;
    private javax.swing.JLabel lblRednibroj;
    private javax.swing.JLabel lblSifraProizvoda;
    private javax.swing.JLabel lblUkupnaNaknada;
    private javax.swing.JPanel panelsp;
    private javax.swing.JTable tblRacun;
    private javax.swing.JTable tblStavkeRacuna;
    private javax.swing.JTextField txtBarkod;
    private javax.swing.JTextField txtBrojPredracuna;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtPoreskaOsnovica;
    private javax.swing.JTextField txtProdajnaCenaSaRabatom;
    private javax.swing.JTextField txtRabat;
    private javax.swing.JTextField txtRedniBroj;
    private javax.swing.JTextField txtRedniBrojStavkePredracuna;
    private javax.swing.JTextField txtSifraProizvoda;
    private javax.swing.JTextField txtSifraRacuna;
    private javax.swing.JTextField txtUkupnaNaknada;
    // End of variables declaration//GEN-END:variables

    private void prepareView() throws Exception {
        setTitle("SDV CODED TEHNIKA OPTIMIZACIJE");
        fillTableRACUNI();
        fillTableSTAVKERACUNA();

    }

    private void fillTableRACUNI() throws Exception {
        List<Racun> racuni = Controller.getInstance().getAllRacuni();
        TableRacun model = new TableRacun(racuni);
        tblRacun.setModel(model);
    }

    private void fillTableSTAVKERACUNA() throws Exception {
        List<StavkaRacuna> stavkeRacuna = Controller.getInstance().getAllStavkeRacuna();
        TableStavkaRacuna model = new TableStavkaRacuna(stavkeRacuna);
        tblStavkeRacuna.setModel(model);
    }

}
