/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import domain.PravnoLice;
import domain.PravnoLiceDetalji;
import domain.PravnoLiceOsnovno;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import tables.TablePravnoLiceDetalji;
import tables.TablePravnoLiceOsnovno;
import view.controller.ViewController;

/**
 *
 * @author trifu
 */
public class FrmVertikalno extends javax.swing.JDialog {

    /**
     * Creates new form FrmVertikalno
     */
    public FrmVertikalno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btnIzmeni.setBackground(Color.PINK);
        btnObrisi.setBackground(Color.PINK);
        btnPopuniPolja.setBackground(Color.PINK);
        btnUnesi.setBackground(Color.PINK);

        try {
            prepareView();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error in view initialization!\n" + e.getMessage(), "View vertikalnp form error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPIB = new javax.swing.JLabel();
        lblNaziv = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblAdresa = new javax.swing.JLabel();
        lblTekuciRacun = new javax.swing.JLabel();
        txtPIB = new javax.swing.JTextField();
        txtNaziv = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        txtAdresa = new javax.swing.JTextField();
        txtTekuciRacun = new javax.swing.JTextField();
        btnUnesi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnPopuniPolja = new javax.swing.JButton();
        lblPravnoLiceDetalji = new javax.swing.JLabel();
        lblPravnoLiceOsnovno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPravnoLiceOsnovno = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPravnoLiceDetalji = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unos,Izmena i Brisanje Pravnog Lica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 153, 153))); // NOI18N

        lblPIB.setText("PIB:");

        lblNaziv.setText("Naziv:");

        lblTelefon.setText("Telefon");

        lblAdresa.setText("Adresa:");

        lblTekuciRacun.setText("Tekuci racun:");

        txtPIB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPIBActionPerformed(evt);
            }
        });

        btnUnesi.setText("Unesi");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnPopuniPolja.setText("Popuni polja za izmenu");
        btnPopuniPolja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopuniPoljaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefon)
                    .addComponent(lblNaziv)
                    .addComponent(lblPIB))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPIB, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(txtNaziv)
                    .addComponent(txtTelefon))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTekuciRacun)
                            .addComponent(lblAdresa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAdresa, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                .addComponent(txtTekuciRacun))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnObrisi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnIzmeni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUnesi)))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPopuniPolja)
                        .addGap(49, 49, 49))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPIB)
                    .addComponent(lblAdresa)
                    .addComponent(txtPIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaziv)
                    .addComponent(lblTekuciRacun)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTekuciRacun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefon)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPopuniPolja)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisi)
                    .addComponent(btnIzmeni)
                    .addComponent(btnUnesi))
                .addContainerGap())
        );

        lblPravnoLiceDetalji.setText("Pravno Lice Detalji");

        lblPravnoLiceOsnovno.setText("Pravno Lice Osnovno");

        tblPravnoLiceOsnovno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPravnoLiceOsnovno);

        tblPravnoLiceDetalji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPravnoLiceDetalji);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPravnoLiceDetalji)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(lblPravnoLiceOsnovno)
                    .addContainerGap(550, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblPravnoLiceDetalji)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(214, 214, 214)
                    .addComponent(lblPravnoLiceOsnovno)
                    .addContainerGap(304, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        try {
            PravnoLice p = new PravnoLice();
            p.setPIB(Long.parseLong(txtPIB.getText().trim()));
            p.setNaziv(txtNaziv.getText().trim());
            p.setTelefon(txtTelefon.getText().trim());
            p.setAdresa(txtAdresa.getText().trim());
            p.setTekuciRacun(txtTekuciRacun.getText().trim());
            Controller.getInstance().addPravnoLiceiew2(p);
            JOptionPane.showMessageDialog(this, "Pravno Lice successfully saved!", "Insert pravno lice", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openFrmVertikalno();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Pravno lice not saved!", "Insert pravno lice", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnUnesiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {
            PravnoLice p = new PravnoLice();
            p.setPIB(Long.parseLong(txtPIB.getText().trim()));
            p.setNaziv(txtNaziv.getText().trim());
            p.setTelefon(txtTelefon.getText().trim());
            p.setAdresa(txtAdresa.getText().trim());
            p.setTekuciRacun(txtTekuciRacun.getText().trim());
            Controller.getInstance().savePravnoLiceView2(p);
            JOptionPane.showMessageDialog(this, "Pravno lice successfully updated!", "Update pravno lice", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openFrmVertikalno();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Pravno lice not updated!", "Update pravno lice", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        try {
            PravnoLice p = new PravnoLice();
            p.setPIB(Integer.parseInt(txtPIB.getText()));

            Controller.getInstance().deletePravnoLiceView2(p);
            JOptionPane.showMessageDialog(this, "Pravno Lice successfully deleted!", "Delete Pravno lice", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openFrmVertikalno();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Pravno lice not deleted!", "Delete Pravno lice", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnPopuniPoljaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopuniPoljaActionPerformed
        popuniPoljaPravnoLice();
    }//GEN-LAST:event_btnPopuniPoljaActionPerformed

    private void txtPIBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPIBActionPerformed

    }//GEN-LAST:event_txtPIBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPopuniPolja;
    private javax.swing.JButton btnUnesi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAdresa;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblPIB;
    private javax.swing.JLabel lblPravnoLiceDetalji;
    private javax.swing.JLabel lblPravnoLiceOsnovno;
    private javax.swing.JLabel lblTekuciRacun;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JTable tblPravnoLiceDetalji;
    private javax.swing.JTable tblPravnoLiceOsnovno;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtPIB;
    private javax.swing.JTextField txtTekuciRacun;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables

    private void prepareView() throws Exception {
        setTitle("VERTIKALNO PARTICIONISANJE");
        fillTableOsnovno();
        fillTableDetalji();
    }

    private void fillTableOsnovno() throws Exception {
        List<PravnoLiceOsnovno> plo = Controller.getInstance().getAllPravnoLiceOsnovno();
        TablePravnoLiceOsnovno model = new TablePravnoLiceOsnovno(plo);
        tblPravnoLiceOsnovno.setModel(model);
    }

    private void fillTableDetalji() throws Exception {
        List<PravnoLiceDetalji> pld = Controller.getInstance().getAllPravnoLiceDetalji();
        TablePravnoLiceDetalji model = new TablePravnoLiceDetalji(pld);
        tblPravnoLiceDetalji.setModel(model);
    }

    private void popuniPoljaPravnoLice() {
        int plo = tblPravnoLiceOsnovno.getSelectedRow();
        int pld = tblPravnoLiceDetalji.getSelectedRow();

        if (plo != -1) {
            pld = -1;
            TablePravnoLiceOsnovno tplo = (TablePravnoLiceOsnovno) tblPravnoLiceOsnovno.getModel();
            PravnoLiceOsnovno osnovno = tplo.getPravnoLiceOsnovno(plo);
            TablePravnoLiceDetalji tpld = (TablePravnoLiceDetalji) tblPravnoLiceDetalji.getModel();
            PravnoLiceDetalji detalji = tpld.getPravnoLice(osnovno);

            txtPIB.setText(osnovno.getPIBO() + "");
            txtNaziv.setText(osnovno.getNaziv());
            if (detalji.getTelefon().equals("")) {
                txtTelefon.setText("");

            } else {
                txtTelefon.setText(detalji.getTelefon());
            }
            if (detalji.getAdresa().equals("")) {
                txtAdresa.setText("");

            } else {
                txtAdresa.setText(detalji.getAdresa());
            }
            if (detalji.getTekuciRacun().equals("")) {
                txtTekuciRacun.setText("");

            } else {
                txtTekuciRacun.setText(detalji.getTekuciRacun());
            }

        }
        if (pld != -1) {
            plo = -1;
            TablePravnoLiceDetalji tpld = (TablePravnoLiceDetalji) tblPravnoLiceDetalji.getModel();
            PravnoLiceDetalji detalji = tpld.getPravnoLiceDetalji(pld);
            TablePravnoLiceOsnovno tplo = (TablePravnoLiceOsnovno) tblPravnoLiceOsnovno.getModel();
            PravnoLiceOsnovno osnovno = tplo.getPravnoLice(detalji);
            txtPIB.setText(detalji.getPIBD() + "");
            if (osnovno.getNaziv().equals("")) {
                txtNaziv.setText("");

            } else {
                txtNaziv.setText(osnovno.getNaziv());
            }
            txtTelefon.setText(detalji.getTelefon());
            txtAdresa.setText(detalji.getAdresa());
            txtTekuciRacun.setText(detalji.getTekuciRacun());

        }

    }
}
