/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import domain.Ponuda;
import domain.StavkaRezervacije;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import tables.TablePonuda;
import tables.TableStavkaRacuna;
import tables.TableStavkaRezervacije;
import view.controller.ViewController;

/**
 *
 * @author trifu
 */
public class NfForma3 extends javax.swing.JDialog {

    /**
     * Creates new form NfForma3
     */
    public NfForma3(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btnIzmeniPonudu.setBackground(Color.PINK);
        btnIzmeniStavkuRezervacije.setBackground(Color.PINK);
        btnPopuniPoljaZaPonudu.setBackground(Color.PINK);
        btnPopuniPoljaZaStavkuRezervacije.setBackground(Color.PINK);
        btnUnesiPonudu.setBackground(Color.PINK);
        btnUnesiStavkuRezervacije.setBackground(Color.PINK);

        try {
            prepareView();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error in view initialization!\n" + e.getMessage(), "View 3nf form error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkaRezervacije = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPonuda = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSifraPonude = new javax.swing.JTextField();
        txtPIB = new javax.swing.JTextField();
        txtGodina = new javax.swing.JTextField();
        btnIzmeniPonudu = new javax.swing.JButton();
        btnPopuniPoljaZaPonudu = new javax.swing.JButton();
        btnUnesiPonudu = new javax.swing.JButton();
        btnIzmeniStavkuRezervacije = new javax.swing.JButton();
        btnPopuniPoljaZaStavkuRezervacije = new javax.swing.JButton();
        btnUnesiStavkuRezervacije = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtRedniBrojStavkeRezervacije = new javax.swing.JTextField();
        txtUkupnaNaknada = new javax.swing.JTextField();
        txtRabat = new javax.swing.JTextField();
        txtBarkod = new javax.swing.JTextField();
        txtKolicinaStavkaRezervacije = new javax.swing.JTextField();
        txtBrojRezervacije = new javax.swing.JTextField();
        txtProdajnaCenaSaRabatom = new javax.swing.JTextField();
        txtSifraProizvoda = new javax.swing.JTextField();
        txtPoreskaOsnovicaStavkaRezervacije = new javax.swing.JTextField();
        txtSifraPonudeStavkaRezervacije = new javax.swing.JTextField();
        txtRedniBrojStavkePonude = new javax.swing.JTextField();
        txtGodinaStavkaRezervacije = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ponuda");

        tblStavkaRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavkaRezervacije);

        jLabel2.setText("Stavka rezervacije");

        tblPonuda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPonuda);

        jLabel3.setText("Sifra ponude:");

        jLabel4.setText("Godina:");

        jLabel5.setText("PIB:");

        txtSifraPonude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSifraPonudeActionPerformed(evt);
            }
        });

        txtPIB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPIBActionPerformed(evt);
            }
        });

        btnIzmeniPonudu.setText("Izmeni");
        btnIzmeniPonudu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniPonuduActionPerformed(evt);
            }
        });

        btnPopuniPoljaZaPonudu.setText("Popuni polja za izmenu");
        btnPopuniPoljaZaPonudu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopuniPoljaZaPonuduActionPerformed(evt);
            }
        });

        btnUnesiPonudu.setText("Unesi");
        btnUnesiPonudu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiPonuduActionPerformed(evt);
            }
        });

        btnIzmeniStavkuRezervacije.setText("Izmeni");
        btnIzmeniStavkuRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniStavkuRezervacijeActionPerformed(evt);
            }
        });

        btnPopuniPoljaZaStavkuRezervacije.setText("Popuni polja za izmenu");
        btnPopuniPoljaZaStavkuRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopuniPoljaZaStavkuRezervacijeActionPerformed(evt);
            }
        });

        btnUnesiStavkuRezervacije.setText("Unesi");
        btnUnesiStavkuRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiStavkuRezervacijeActionPerformed(evt);
            }
        });

        jLabel6.setText("Redni broj stavke rezervacije");

        jLabel7.setText("Kolicina:");

        jLabel8.setText("Broj rezervacije:");

        jLabel9.setText("Rabat:");

        jLabel10.setText("Barkod:");

        jLabel11.setText("Ukupna naknada:");

        jLabel12.setText("Godina:");

        jLabel13.setText("Sifra ponude:");

        jLabel14.setText("Redni broj stavke ponude:");

        jLabel15.setText("Prodajna cena sa rabatom:");

        jLabel16.setText("Poreska osnovica:");

        jLabel17.setText("Sifra proizvoda:");

        txtKolicinaStavkaRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKolicinaStavkaRezervacijeActionPerformed(evt);
            }
        });

        txtGodinaStavkaRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGodinaStavkaRezervacijeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSifraPonude, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPIB, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnIzmeniPonudu)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnUnesiPonudu))
                                            .addComponent(btnPopuniPoljaZaPonudu))
                                        .addGap(194, 194, 194))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17))
                                        .addGap(46, 46, 46))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(222, 222, 222)
                                                        .addComponent(jLabel12))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(163, 163, 163)
                                                        .addComponent(jLabel14)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(63, 63, 63)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPoreskaOsnovicaStavkaRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSifraProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRedniBrojStavkePonude, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSifraPonudeStavkaRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGodinaStavkaRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProdajnaCenaSaRabatom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnPopuniPoljaZaStavkuRezervacije)
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIzmeniStavkuRezervacije)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(42, 42, 42))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(74, 74, 74))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel7))
                                        .addGap(83, 83, 83))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(62, 62, 62))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(92, 92, 92)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtRedniBrojStavkeRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtRabat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtBrojRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKolicinaStavkaRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUkupnaNaknada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtBarkod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(142, 142, 142)
                        .addComponent(btnUnesiStavkuRezervacije)
                        .addGap(191, 191, 191))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnPopuniPoljaZaPonudu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnIzmeniPonudu)
                                    .addComponent(btnUnesiPonudu)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtProdajnaCenaSaRabatom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPoreskaOsnovicaStavkaRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtSifraProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtRedniBrojStavkePonude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSifraPonudeStavkaRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtGodinaStavkaRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtRedniBrojStavkeRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtBrojRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtKolicinaStavkaRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtBarkod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtUkupnaNaknada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtRabat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9)
                                            .addComponent(btnPopuniPoljaZaStavkuRezervacije))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUnesiStavkuRezervacije)
                            .addComponent(btnIzmeniStavkuRezervacije))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSifraPonude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSifraPonudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifraPonudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSifraPonudeActionPerformed

    private void txtPIBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPIBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPIBActionPerformed

    private void btnIzmeniPonuduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniPonuduActionPerformed
        try {
            Ponuda p = new Ponuda();
            p.setSifraPonude(Long.parseLong(txtSifraPonude.getText().trim()));
            p.setGodina(Integer.parseInt(txtGodina.getText().trim()));
            p.setPIB(Long.parseLong(txtPIB.getText().trim()));
            Controller.getInstance().savePonudu(p);
            JOptionPane.showMessageDialog(this, "Ponuda successfully updated!", "Update narudzbenica", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openNfForma3();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ponuda not updated!", "Update Ponuda", JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_btnIzmeniPonuduActionPerformed

    private void btnPopuniPoljaZaPonuduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopuniPoljaZaPonuduActionPerformed
        popuniPonudu();
    }//GEN-LAST:event_btnPopuniPoljaZaPonuduActionPerformed

    private void btnUnesiPonuduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiPonuduActionPerformed
        try {
            Ponuda p = new Ponuda();
            p.setSifraPonude(Integer.parseInt(txtSifraPonude.getText().trim()));
            p.setGodina(Integer.parseInt(txtGodina.getText().trim()));

            p.setPIB(Integer.parseInt(txtPIB.getText().trim()));
            Controller.getInstance().addPonuda(p);
            JOptionPane.showMessageDialog(this, "Ponuda successfully saved!", "Insert ponuda", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openNfForma3();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ponuda not saved!", "Insert ponuda", JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_btnUnesiPonuduActionPerformed

    private void btnIzmeniStavkuRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniStavkuRezervacijeActionPerformed
        try {
            StavkaRezervacije sr = new StavkaRezervacije();
            sr.setRedniBrojStavkeRezervacije(Long.parseLong(txtRedniBrojStavkeRezervacije.getText()));
            sr.setBrojRezervacije(Long.parseLong(txtBrojRezervacije.getText()));
            sr.setKolicina(Integer.parseInt(txtKolicinaStavkaRezervacije.getText()));
            sr.setBarkod(txtBarkod.getText());
            sr.setUkupnaNaknada(Double.parseDouble(txtUkupnaNaknada.getText()));
            sr.setRabat(Double.parseDouble(txtRabat.getText()));
            sr.setProdajnaCenaSaRabatom(Double.parseDouble(txtProdajnaCenaSaRabatom.getText()));
            sr.setPoreskaOsnovica(Double.parseDouble(txtPoreskaOsnovicaStavkaRezervacije.getText()));
            sr.setSifraProizvoda(Long.parseLong(txtSifraProizvoda.getText()));
            sr.setRedniBrojStavkePonude(Long.parseLong(txtRedniBrojStavkePonude.getText()));
            sr.setSifraPonude(Long.parseLong(txtSifraPonudeStavkaRezervacije.getText()));
            sr.setGodina(Integer.parseInt(txtGodinaStavkaRezervacije.getText()));

            Controller.getInstance().saveStavkaRezervacije(sr);
            JOptionPane.showMessageDialog(this, "Stavka rezervacije successfully saved!", "Insert stavka rezervacije", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openNfForma3();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Stavka rezervacije not saved!", "Insert stavka rezervacije", JOptionPane.ERROR_MESSAGE);
        }     }//GEN-LAST:event_btnIzmeniStavkuRezervacijeActionPerformed

    private void btnPopuniPoljaZaStavkuRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopuniPoljaZaStavkuRezervacijeActionPerformed
        popuniStavkuRezervacie();
    }//GEN-LAST:event_btnPopuniPoljaZaStavkuRezervacijeActionPerformed

    private void btnUnesiStavkuRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiStavkuRezervacijeActionPerformed
        try {
            StavkaRezervacije sr = new StavkaRezervacije();
            sr.setRedniBrojStavkeRezervacije(Long.parseLong(txtRedniBrojStavkeRezervacije.getText()));
            sr.setBrojRezervacije(Long.parseLong(txtBrojRezervacije.getText()));
            sr.setKolicina(Integer.parseInt(txtKolicinaStavkaRezervacije.getText()));
            sr.setBarkod(txtBarkod.getText());
            sr.setUkupnaNaknada(Double.parseDouble(txtUkupnaNaknada.getText()));
            sr.setRabat(Double.parseDouble(txtRabat.getText()));
            sr.setProdajnaCenaSaRabatom(Double.parseDouble(txtProdajnaCenaSaRabatom.getText()));
            sr.setPoreskaOsnovica(Double.parseDouble(txtPoreskaOsnovicaStavkaRezervacije.getText()));
            sr.setSifraProizvoda(Long.parseLong(txtSifraProizvoda.getText()));
            sr.setRedniBrojStavkePonude(Long.parseLong(txtRedniBrojStavkePonude.getText()));
            sr.setSifraPonude(Long.parseLong(txtSifraPonudeStavkaRezervacije.getText()));
            Controller.getInstance().addStavkaRezervacije(sr);
            JOptionPane.showMessageDialog(this, "Stavka rezervacije successfully saved!", "Insert stavka rezervacije", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            ViewController.getInstance().openNfForma3();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Stavka rezervacije not saved!", "Insert stavka rezervacije", JOptionPane.ERROR_MESSAGE);
        }     }//GEN-LAST:event_btnUnesiStavkuRezervacijeActionPerformed

    private void txtGodinaStavkaRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGodinaStavkaRezervacijeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGodinaStavkaRezervacijeActionPerformed

    private void txtKolicinaStavkaRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKolicinaStavkaRezervacijeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKolicinaStavkaRezervacijeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniPonudu;
    private javax.swing.JButton btnIzmeniStavkuRezervacije;
    private javax.swing.JButton btnPopuniPoljaZaPonudu;
    private javax.swing.JButton btnPopuniPoljaZaStavkuRezervacije;
    private javax.swing.JButton btnUnesiPonudu;
    private javax.swing.JButton btnUnesiStavkuRezervacije;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPonuda;
    private javax.swing.JTable tblStavkaRezervacije;
    private javax.swing.JTextField txtBarkod;
    private javax.swing.JTextField txtBrojRezervacije;
    private javax.swing.JTextField txtGodina;
    private javax.swing.JTextField txtGodinaStavkaRezervacije;
    private javax.swing.JTextField txtKolicinaStavkaRezervacije;
    private javax.swing.JTextField txtPIB;
    private javax.swing.JTextField txtPoreskaOsnovicaStavkaRezervacije;
    private javax.swing.JTextField txtProdajnaCenaSaRabatom;
    private javax.swing.JTextField txtRabat;
    private javax.swing.JTextField txtRedniBrojStavkePonude;
    private javax.swing.JTextField txtRedniBrojStavkeRezervacije;
    private javax.swing.JTextField txtSifraPonude;
    private javax.swing.JTextField txtSifraPonudeStavkaRezervacije;
    private javax.swing.JTextField txtSifraProizvoda;
    private javax.swing.JTextField txtUkupnaNaknada;
    // End of variables declaration//GEN-END:variables

    private void prepareView() throws Exception {
        setTitle("3NF");
        fillTablePonude();
        filTableStavkeRezervacije();
    }

    private void fillTablePonude() throws Exception {
        List<Ponuda> ponude = Controller.getInstance().getAllPonude();
        TablePonuda model = new TablePonuda(ponude);
        tblPonuda.setModel(model);
    }

    private void filTableStavkeRezervacije() throws Exception {
        List<StavkaRezervacije> stavkeRezervacije = Controller.getInstance().getAllStavkeRezervacije();
        TableStavkaRezervacije model = new TableStavkaRezervacije(stavkeRezervacije);
        tblStavkaRezervacije.setModel(model);
    }

    private void popuniStavkuRezervacie() {
        int r = tblStavkaRezervacije.getSelectedRow();
        TableStavkaRezervacije tsr = (TableStavkaRezervacije) tblStavkaRezervacije.getModel();
        StavkaRezervacije stavkaRezervacije = tsr.getStavkaRezervacije(r);

        txtRedniBrojStavkeRezervacije.setText(stavkaRezervacije.getRedniBrojStavkeRezervacije() + "");
        txtBrojRezervacije.setText(stavkaRezervacije.getBrojRezervacije() + "");
        txtKolicinaStavkaRezervacije.setText(stavkaRezervacije.getKolicina() + "");

        txtBarkod.setText(stavkaRezervacije.getBarkod() + "");
        txtUkupnaNaknada.setText(stavkaRezervacije.getUkupnaNaknada() + "");
        txtRabat.setText(stavkaRezervacije.getRabat() + "");

        txtProdajnaCenaSaRabatom.setText(stavkaRezervacije.getProdajnaCenaSaRabatom() + "");
        txtPoreskaOsnovicaStavkaRezervacije.setText(stavkaRezervacije.getPoreskaOsnovica() + "");

        txtSifraProizvoda.setText(stavkaRezervacije.getSifraProizvoda() + "");
        txtRedniBrojStavkePonude.setText(stavkaRezervacije.getRedniBrojStavkePonude() + "");
        txtSifraPonudeStavkaRezervacije.setText(stavkaRezervacije.getSifraPonude() + "");

        txtGodinaStavkaRezervacije.setText(stavkaRezervacije.getGodina() + "");
    }

    private void popuniPonudu() {
        int r = tblPonuda.getSelectedRow();
        TablePonuda tsr = (TablePonuda) tblPonuda.getModel();
        Ponuda ponuda = tsr.getPonuda(r);

        txtSifraPonude.setText(ponuda.getSifraPonude() + "");
        txtGodina.setText(ponuda.getGodina() + "");
        txtPIB.setText(ponuda.getPIB() + "");
    }
}
